# Generated by Django 2.0 on 2017-12-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_date', models.DateTimeField()),
                ('line_num', models.CharField(max_length=10)),
                ('station_id', models.IntegerField()),
                ('station_name', models.CharField(max_length=30)),
                ('paid_on', models.PositiveIntegerField()),
                ('paid_off', models.PositiveIntegerField()),
                ('unpaid_on', models.PositiveIntegerField()),
                ('unpaid_off', models.PositiveIntegerField()),
                ('submit_date', models.DateTimeField()),
            ],
        ),
    ]
